# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.

  version: '3'
  services:
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - .:/var/www/html
        - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
    php:
      image: php:8.3-fpm
      volumes:
        - .:/var/www/html
