version: '3'
services:
  server:
    build: 
      context: ./server
      args:
        API_BASE_URL: ${API_BASE_URL}
    ports:
      - ${SERVER_PORT}:${SERVER_INTERNAL_PORT}
  client:
    build: 
      context: ./client
      args:
        API_BASE_URL: ${API_BASE_URL}
    ports:
      - ${CLIENT_PORT}:${SERVER_INTERNAL_PORT}
    depends_on:
      - server