version: '3'
services:
  server:
    build: ./server
    ports:
      - 3001:3000
  client:
    build: 
      context: ./client
      args:
        API_BASE_URL: http://server:3000
    ports:
      - 3000:3000
    depends_on:
      - server